package chikoski:glitch;

interface types {
    record scan-line {
        data: list<u8>,
    }
    enum filter-type {
        none,
        add,
        sub,
        average,
        paeth,
    }
}

world client {
    use types.{scan-line};

    export glitch-scan-line: func(line: scan-line);
}