[package]
name = "png-glitch-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = [] }
clap = { version = "4.5.7", features = ["derive"] }
png-glitch = { path = "crates/png-glitch" }