[package]
authors = ["N.Shimizu <chikoski@gmail.com>"]
edition = "2018"
name = "png_glitch"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
env_logger = "0.7.1"
flate2 = "1.0.17"
log = "0.4.11"
