[package]
name = "png-glitch"
version = "0.1.2"
edition = "2021"
authors = ["N.Shimizu <chikoski@gmail.com>"]
description = "A library to glitch PNG images."
license = "MIT"
readme = "README.md"
repository = "https://github.com/chikoski/png-glitch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
flate2 = { version = "1.0.28", features = ["zlib"] }
thiserror = "1.0.56"
