[package]
name = "png-glitch"
version = "0.6.0"
edition = "2021"
authors = ["N.Shimizu <chikoski@gmail.com>"]
description = "A library to glitch PNG images."
license = "MIT"
readme = "README.md"
repository = "https://github.com/chikoski/png-glitch"

[dependencies]
anyhow = "1.0.100"
crc32fast = "1.5.0"
fdeflate = "0.3.7"
rayon = "1.12.0"
thiserror = "2.0.17"
